
POST http://localhost:3001/users
Content-Type: application/json

{
	"firstName": "user1",
    "lastName": "montana",
    "type": "consumer",
    "userName": "user1",
    "password":"taliban"
}

###

GET http://localhost:3001/users/d8513186a836458fb1eb1700d5ff1f51


###


GET http://localhost:3000/users
###

DELETE  http://localhost:3000/users/c869774afbfa4ffb97fade90c12c5cf7
###

POST   http://localhost:3000/login
Content-Type: application/json

{
    "userName": "Deybee",
    "password": "intituition"

}


###

POST   http://localhost:3001/signup
Content-Type: application/json

{
	"firstName": "adebola",
    "lastName": "Aderemi",
    "userName": "Deybeeee",
    "password": "intituition",
    "type": "consumer"
}
###eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODg1NjA4MDV9.D1bvlFDbPgdjY6cHWrJYfKoU6fHJS3SOszWoywssjuo
###
POST  http://localhost:3001/room/initiate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5NDIwMGRkODY0ODk0ZTg5YTIyZmYzMTM0YTg3NDkyNiIsInVzZXJUeXBlIjoiY29uc3VtZXIiLCJpYXQiOjE2ODc0MjU1OTZ9.H1jMMU28VuRMQYtems9TPXbIkschEeoxN_sy2r_PzLM

{
    "userIds": ["62da4e29ff554176bec7745fc7d331b7"],
    "type": "consumer-to-consumer"
    
}
###

POST http://localhost:3001/room/9bae87c843e24854894e989c5e8c3476/message
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5NDIwMGRkODY0ODk0ZTg5YTIyZmYzMTM0YTg3NDkyNiIsInVzZXJUeXBlIjoiY29uc3VtZXIiLCJpYXQiOjE2ODc0MjU1OTZ9.H1jMMU28VuRMQYtems9TPXbIkschEeoxN_sy2r_PzLM

{
    "messageText": "heyplayer"
}


###

GET http://localhost:3001/room/9bae87c843e24854894e989c5e8c3476
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5NDIwMGRkODY0ODk0ZTg5YTIyZmYzMTM0YTg3NDkyNiIsInVzZXJUeXBlIjoiY29uc3VtZXIiLCJpYXQiOjE2ODc0MjU1OTZ9.H1jMMU28VuRMQYtems9TPXbIkschEeoxN_sy2r_PzLM

###

GET http://localhost:3000/room
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5NDIwMGRkODY0ODk0ZTg5YTIyZmYzMTM0YTg3NDkyNiIsInVzZXJUeXBlIjoiY29uc3VtZXIiLCJpYXQiOjE2ODc0MjU1OTZ9.H1jMMU28VuRMQYtems9TPXbIkschEeoxN_sy2r_PzLM


